apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webapp-secrets-manager
rules:
  - apiGroups:
      - ""
      #- rbac.authorization.k8s.io
    resources:
      - secrets
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
