apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webappp-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: webapp-service-account 
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webapp-secrets-manager
