apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-testing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.rex/name: webapp-example
    #matchExpressions:
    #  - {key: "app.rex/name", operator: In, values: [webapp-example]}
  template:
    metadata:
      labels:
        app.rex/name: webapp-example
    spec:
      containers:
        - name: webapp-example-node
          image: rexresurreccionhome/webapp-for-testing:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /home/webapp/logs
              name: webapp-example-volume
          env:
            - name: USER_SECRETS
              valueFrom:
                secretKeyRef:
                  name: webapp.some.random.unique.identifier
                  key: userSecrets
          readinessProbe:
            httpGet:
              path: /status
              port: 8080
            periodSeconds: 15
            initialDelaySeconds: 2
          livenessProbe:
            httpGet:
              path: /status
              port: 8080
            periodSeconds: 30
            initialDelaySeconds: 5 
      volumes:
        - name: webapp-example-volume
          emptyDir: {}
      serviceAccountName: webapp-service-account
