apiVersion: v1
kind: Service
metadata:
  name: webapp-testing
spec:
  selector:
    app.rex/name: webapp-example    
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer


